version: "3.4"
services:
  web:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./docs/:/usr/share/nginx/html
    ports:
      - "8084:80"
    restart : always
